# Generated by Django 2.2.4 on 2021-08-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210828_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ip',
        ),
    ]
